import turtle
size = 1.7
for i in range(60):
 turtle.pensize(5)
 turtle.penup()
 turtle.forward(200*size)
 turtle.pendown()
 turtle.forward(5*size)
 turtle.penup()
 turtle.backward(205*size)
 turtle.right(6)

for i in range(12):
 turtle.pensize(10)
 turtle.penup()
 turtle.forward(200*size)
 turtle.pendown()
 turtle.forward(10*size)
 turtle.penup()
 turtle.backward(210*size)
 turtle.left(360/12)

import time
now= time.gmtime(time.time())
turtle.home()
turtle.pd()
turtle.left(90)
turtle.pensize(3)
turtle.color("red")
turtle.right(now.tm_sec*6)
turtle.backward(30*size)
turtle.forward(190*size)
turtle.home()
turtle.pd()
turtle.left(90)
turtle.pensize(6)
turtle.color("black")
turtle.right(now.tm_min*6+now.tm_sec*(6/60))
turtle.backward(30*size)
turtle.forward(175*size)
turtle.home()
turtle.left(90)
turtle.color("black")
turtle.pensize(10)
turtle.right(((now.tm_hour + 9) % 12) *
(360/12) + now.tm_min * (30/60))
turtle.backward(30*size)
turtle.forward(160*size)
turtle.hideturtle()
